/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collisiondetectionupdate;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author saliya
 */
public class Ui extends javax.swing.JFrame implements KeyListener {

    private int X = 20;
    private int Y = 40;
    private Dimension FRAME_SIZE;

    private Rectangle R1 = new Rectangle(0, 0, 50, 50);
    private Rectangle R2 = new Rectangle(0, 0, 100, 100);
    private BufferedImage BUFFERED_IMAGE = new BufferedImage(5, 5, BufferedImage.TYPE_INT_RGB);

    private Graphics2D G2D;
    boolean FIRST_RUN = true;

    Rectangle AREA_CLEAR;

    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
        addKeyListener(this);
        FRAME_SIZE = this.getContentPane().getSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("collision Detection Update");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ui().setVisible(true);
        });
    }

    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_UP:
                if (Y < 1) {
                    return;
                }
                Y--;
                break;
            case KeyEvent.VK_DOWN:
                if (Y > FRAME_SIZE.getHeight() - 90) {
                    return;
                }
                Y++;
                break;
            case KeyEvent.VK_LEFT:
                if (X < 1) {
                    return;
                }
                X--;
                break;
            case KeyEvent.VK_RIGHT:
                if (X > FRAME_SIZE.getWidth() - 66) {
                    return;
                }
                X++;
                break;
            default:
                break;
        }
        updateLocation(X, Y);
    }

    @Override
    public void keyReleased(KeyEvent e) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  @Override
    public void paint(Graphics g) {
        update(g);
    }

    @Override
    public void update(Graphics g) {
        Graphics2D G2 = (Graphics2D) g;

        if (FIRST_RUN) {
            AREA_CLEAR = new Rectangle(FRAME_SIZE);
            BUFFERED_IMAGE = (BufferedImage) createImage(FRAME_SIZE.width, FRAME_SIZE.height);
            G2D = BUFFERED_IMAGE.createGraphics();
            R1.setLocation(X, Y);
            R2.setLocation(((int) FRAME_SIZE.getWidth() / 2) - 100 / 2, ((int) FRAME_SIZE.getHeight() / 2) - 100 / 2);
            FIRST_RUN = false;
        }

        G2D.setColor(Color.white);
        G2D.clearRect(0, 0, AREA_CLEAR.width, AREA_CLEAR.height);

        G2D.setPaint(Color.RED);
        G2D.draw(R1);
        G2D.setPaint(Color.RED);
        G2D.fill(R1);

        G2D.setPaint(Color.BLUE);
        G2D.draw(R2);
        G2D.setPaint(Color.BLUE);
        G2D.fill(R2);

        if (R1.intersects(R2)) {
            G2D.setColor(Color.BLACK);
            G2D.setFont(new Font("default", Font.BOLD, 16));
            G2D.drawString("collision !", 150, 50);
        } else {

        }

        G2.drawImage(BUFFERED_IMAGE, 0, 0, this);

    }

    public void updateLocation(int X, int Y) {
        R1.setLocation(X, Y);
        repaint();
    }
}
